version: '3.8'
services:
  indivest-mf-go:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./logs/indivest-mf-go:/app/logs
    restart: always

networks:
  default:
    external:
      name: dockerhome