package seeders

import (
	"fmt"
	"indivest-engine/models"
	"indivest-engine/utils"
)

func (s *Seeder) FatcaCountryCode() error {
	l := []models.FatcaCountryCode{
		{1, "AF", "Afghanistan"},
		{2, "AX", "Aland Islands"},
		{3, "AL", "Albania"},
		{4, "DZ", "Algeria"},
		{5, "AS", "American Samoa"},
		{6, "AD", "Andorra"},
		{7, "AO", "Angola"},
		{8, "AI", "Anguilla"},
		{9, "AQ", "Antarctica"},
		{10, "AG", "Antigua And Barbuda"},
		{11, "AR", "Argentina"},
		{12, "AM", "Armenia"},
		{13, "AW", "Aruba"},
		{14, "AU", "Australia"},
		{15, "AT", "Austria"},
		{16, "AZ", "Azerbaijan"},
		{17, "BS", "Bahamas"},
		{18, "BH", "Bahrain"},
		{19, "BD", "Bangladesh"},
		{20, "BB", "Barbados"},
		{21, "BY", "Belarus"},
		{22, "BE", "Belgium"},
		{23, "BZ", "Belize"},
		{24, "BJ", "Benin"},
		{25, "BM", "Bermuda"},
		{26, "BT", "Bhutan"},
		{27, "BO", "Bolivia"},
		{28, "BQ", "Bonaire, Sint Eustatius And Saba"},
		{29, "BA", "Bosnia And Herzegovina"},
		{30, "BW", "Botswana"},
		{31, "BV", "Bouvet Island"},
		{32, "BR", "Brazil"},
		{33, "IO", "British Indian Ocean Territory"},
		{34, "BN", "Brunei Darussalam"},
		{35, "BG", "Bulgaria"},
		{36, "BF", "Burkina Faso"},
		{37, "BI", "Burundi"},
		{38, "KH", "Cambodia"},
		{39, "CM", "Cameroon"},
		{40, "CA", "Canada"},
		{41, "CV", "Cape Verde"},
		{42, "KY", "Cayman Islands"},
		{43, "CF", "Central African Republic"},
		{44, "TD", "Chad"},
		{45, "CL", "Chile"},
		{46, "CN", "China"},
		{47, "CX", "Christmas Island"},
		{48, "CC", "Cocos (Keeling) Islands"},
		{49, "CO", "Colombia"},
		{50, "KM", "Comoros"},
		{51, "CG", "Congo"},
		{52, "CD", "Congo, The Democratic Republic Of The"},
		{53, "CK", "Cook Islands"},
		{54, "CR", "Costa Rica"},
		{55, "CI", "Cote D'Ivoire"},
		{56, "HR", "Croatia"},
		{57, "CU", "Cuba"},
		{58, "CW", "Curacao"},
		{59, "CY", "Cyprus"},
		{60, "CZ", "Czech Republic"},
		{61, "DK", "Denmark"},
		{62, "DJ", "Djibouti"},
		{63, "DM", "Dominica"},
		{64, "DO", "Dominican Republic"},
		{65, "EC", "Ecuador"},
		{66, "EG", "Egypt"},
		{67, "SV", "El Salvador"},
		{68, "GQ", "Equatorial Guinea"},
		{69, "ER", "Eritrea"},
		{70, "EE", "Estonia"},
		{71, "ET", "Ethiopia"},
		{72, "FK", "Falkland Islands (Malvinas)"},
		{73, "FO", "Faroe Islands"},
		{74, "FJ", "Fiji"},
		{75, "FI", "Finland"},
		{76, "FR", "France"},
		{77, "GF", "French Guiana"},
		{78, "PF", "French Polynesia"},
		{79, "TF", "French Southern Territories"},
		{80, "GA", "Gabon"},
		{81, "GM", "Gambia"},
		{82, "GE", "Georgia"},
		{83, "DE", "Germany"},
		{84, "GH", "Ghana"},
		{85, "GI", "Gibraltar"},
		{86, "GR", "Greece"},
		{87, "GL", "Greenland"},
		{88, "GD", "Grenada"},
		{89, "GP", "Guadeloupe"},
		{90, "GU", "Guam"},
		{91, "GT", "Guatemala"},
		{92, "GG", "Guernsey"},
		{93, "GN", "Guinea"},
		{94, "GW", "Guinea-Bissau"},
		{95, "GY", "Guyana"},
		{96, "HT", "Haiti"},
		{97, "HM", "Heard Island And Mcdonald Islands"},
		{98, "HN", "Honduras"},
		{99, "HK", "Hong Kong"},
		{100, "HU", "Hungary"},
		{101, "IS", "Iceland"},
		{102, "IN", "India"},
		{103, "ID", "Indonesia"},
		{104, "IR", "Iran, Islamic Republic Of"},
		{105, "IQ", "Iraq"},
		{106, "IE", "Ireland"},
		{107, "IM", "Isle Of Man"},
		{108, "IL", "Israel"},
		{109, "IT", "Italy"},
		{110, "JM", "Jamaica"},
		{111, "JP", "Japan"},
		{112, "JE", "Jersey"},
		{113, "JO", "Jordan"},
		{114, "KZ", "Kazakhstan"},
		{115, "KE", "Kenya"},
		{116, "KI", "Kiribati"},
		{117, "KP", "Korea, Democratic People's Republic Of"},
		{118, "KR", "Korea, Republic Of"},
		{119, "KW", "Kuwait"},
		{120, "KG", "Kyrgyzstan"},
		{121, "LA", "Lao People's Democratic Republic"},
		{122, "LV", "Latvia"},
		{123, "LB", "Lebanon"},
		{124, "LS", "Lesotho"},
		{125, "LR", "Liberia"},
		{126, "LY", "Libyan Arab Jamahiriya"},
		{127, "LI", "Liechtenstein"},
		{128, "LT", "Lithuania"},
		{129, "LU", "Luxembourg"},
		{130, "MO", "Macao"},
		{131, "MK", "Macedonia, The Former Yugoslav Republic Of"},
		{132, "MG", "Madagascar"},
		{133, "MW", "Malawi"},
		{134, "MY", "Malaysia"},
		{135, "MV", "Maldives"},
		{136, "ML", "Mali"},
		{137, "MT", "Malta"},
		{138, "MH", "Marshall Islands"},
		{139, "MQ", "Martinique"},
		{140, "MR", "Mauritania"},
		{141, "MU", "Mauritius"},
		{142, "YT", "Mayotte"},
		{143, "MX", "Mexico"},
		{144, "FM", "Micronesia, Federated States Of"},
		{145, "MD", "Moldova, Republic Of"},
		{146, "MC", "Monaco"},
		{147, "MN", "Mongolia"},
		{148, "ME", "Montenegro"},
		{149, "MS", "Montserrat"},
		{150, "MA", "Morocco"},
		{151, "MZ", "Mozambique"},
		{152, "MM", "Myanmar"},
		{153, "nan", "Namibia"},
		{154, "NR", "Nauru"},
		{155, "NP", "Nepal"},
		{156, "NL", "Netherlands"},
		{157, "AN", "Netherlands Antilles"},
		{158, "NC", "New Caledonia"},
		{159, "NZ", "New Zealand"},
		{160, "NI", "Nicaragua"},
		{161, "NE", "Niger"},
		{162, "NG", "Nigeria"},
		{163, "NU", "Niue"},
		{164, "NF", "Norfolk Island"},
		{165, "MP", "Northern Mariana Islands"},
		{166, "NO", "Norway"},
		{167, "XX", "Not categorised"},
		{168, "OM", "Oman"},
		{169, "ZZ", "Others"},
		{170, "PK", "Pakistan"},
		{171, "PW", "Palau"},
		{172, "PS", "Palestinian Territory, Occupied"},
		{173, "PA", "Panama"},
		{174, "PG", "Papua New Guinea"},
		{175, "PY", "Paraguay"},
		{176, "PE", "Peru"},
		{177, "PH", "Philippines"},
		{178, "PN", "Pitcairn"},
		{179, "PL", "Poland"},
		{180, "PT", "Portugal"},
		{181, "PR", "Puerto Rico"},
		{182, "QA", "Qatar"},
		{183, "RE", "Reunion Island"},
		{184, "RO", "Romania"},
		{185, "RU", "Russian Federation"},
		{186, "RW", "Rwanda"},
		{187, "BL", "Saint Barthelemy"},
		{188, "SH", "Saint Helena, Ascension And Tristan da Cunha"},
		{189, "KN", "Saint Kitts And Nevis"},
		{190, "LC", "Saint Lucia"},
		{191, "MF", "Saint Martin"},
		{192, "PM", "Saint Pierre And Miquelon"},
		{193, "VC", "Saint Vincent And The Grenadines"},
		{194, "WS", "Samoa"},
		{195, "SM", "San Marino"},
		{196, "ST", "Sao Tome And Principe"},
		{197, "SA", "Saudi Arabia"},
		{198, "SN", "Senegal"},
		{199, "RS", "Serbia"},
		{200, "SC", "Seychelles"},
		{201, "SL", "Sierra Leone"},
		{202, "SG", "Singapore"},
		{203, "SX", "Sint Maarten (Dutch Part)"},
		{204, "SK", "Slovakia"},
		{205, "SI", "Slovenia"},
		{206, "SB", "Solomon Islands"},
		{207, "SO", "Somalia"},
		{208, "ZA", "South Africa"},
		{209, "GS", "South Georgia And The South Sandwich Islands"},
		{210, "SS", "South Sudan"},
		{211, "ES", "Spain"},
		{212, "LK", "Sri Lanka"},
		{213, "SD", "Sudan"},
		{214, "SR", "Suriname"},
		{215, "SJ", "Svalbard And Jan Mayen Islands"},
		{216, "SZ", "Swaziland"},
		{217, "SE", "Sweden"},
		{218, "CH", "Switzerland"},
		{219, "SY", "Syrian Arab Republic"},
		{220, "TW", "Taiwan, Province Of China"},
		{221, "TJ", "Tajikistan"},
		{222, "TZ", "Tanzania, United Republic Of"},
		{223, "TH", "Thailand"},
		{224, "TL", "Timor-Leste"},
		{225, "TG", "Togo"},
		{226, "TK", "Tokelau"},
		{227, "TO", "Tonga"},
		{228, "TT", "Trinidad And Tobago"},
		{229, "TN", "Tunisia"},
		{230, "TR", "Turkey"},
		{231, "TM", "Turkmenistan"},
		{232, "TC", "Turks And Caicos Islands"},
		{233, "TV", "Tuvalu"},
		{234, "UG", "Uganda"},
		{235, "UA", "Ukraine"},
		{236, "AE", "United Arab Emirates"},
		{237, "GB", "United Kingdom"},
		{238, "US", "United States"},
		{239, "UM", "United States Minor Outlying Islands"},
		{240, "UY", "Uruguay"},
		{241, "UZ", "Uzbekistan"},
		{242, "VU", "Vanuatu"},
		{243, "VA", "Vatican City State"},
		{244, "VE", "Venezuela, Bolivarian Republic Of"},
		{245, "VN", "Viet Nam"},
		{246, "VG", "Virgin Islands, British"},
		{247, "VI", "Virgin Islands, U.S."},
		{248, "WF", "Wallis And Futuna"},
		{249, "EH", "Western Sahara"},
		{250, "YE", "Yemen"},
		{251, "ZM", "Zambia"},
		{252, "ZW", "Zimbabwe"},
	}
	for _, lis := range l {
		err := s.db.Store.Create(&lis)
		//if err != nil && err.Error.Error() == {
		//	fmt.Println(err.Error)
		//	utils.Log.Error(err)
		//}
		if err.Error != nil {
			fmt.Println(err.Error)
			utils.Log.Error(err)
		}
		//else {
		//	return err.Error
		//}
	}
	return nil
}
