package seeders

import (
	"indivest-engine/models"
	"indivest-engine/utils"
)

func (s *Seeder) FatcaCountryCode() error {
	l := []models.FatcaCountryCode{
		{Id: 1, Code: "AF", Description: "Afghanistan"},
		{Id: 2, Code: "AX", Description: "Aland Islands"},
		{Id: 3, Code: "AL", Description: "Albania"},
		{Id: 4, Code: "DZ", Description: "Algeria"},
		{Id: 5, Code: "AS", Description: "American Samoa"},
		{Id: 6, Code: "AD", Description: "Andorra"},
		{Id: 7, Code: "AO", Description: "Angola"},
		{Id: 8, Code: "AI", Description: "Anguilla"},
		{Id: 9, Code: "AQ", Description: "Antarctica"},
		{Id: 10, Code: "AG", Description: "Antigua And Barbuda"},
		{Id: 11, Code: "AR", Description: "Argentina"},
		{Id: 12, Code: "AM", Description: "Armenia"},
		{Id: 13, Code: "AW", Description: "Aruba"},
		{Id: 14, Code: "AU", Description: "Australia"},
		{Id: 15, Code: "AT", Description: "Austria"},
		{Id: 16, Code: "AZ", Description: "Azerbaijan"},
		{Id: 17, Code: "BS", Description: "Bahamas"},
		{Id: 18, Code: "BH", Description: "Bahrain"},
		{Id: 19, Code: "BD", Description: "Bangladesh"},
		{Id: 20, Code: "BB", Description: "Barbados"},
		{Id: 21, Code: "BY", Description: "Belarus"},
		{Id: 22, Code: "BE", Description: "Belgium"},
		{Id: 23, Code: "BZ", Description: "Belize"},
		{Id: 24, Code: "BJ", Description: "Benin"},
		{Id: 25, Code: "BM", Description: "Bermuda"},
		{Id: 26, Code: "BT", Description: "Bhutan"},
		{Id: 27, Code: "BO", Description: "Bolivia"},
		{Id: 28, Code: "BQ", Description: "Bonaire, Sint Eustatius And Saba"},
		{Id: 29, Code: "BA", Description: "Bosnia And Herzegovina"},
		{Id: 30, Code: "BW", Description: "Botswana"},
		{Id: 31, Code: "BV", Description: "Bouvet Island"},
		{Id: 32, Code: "BR", Description: "Brazil"},
		{Id: 33, Code: "IO", Description: "British Indian Ocean Territory"},
		{Id: 34, Code: "BN", Description: "Brunei Darussalam"},
		{Id: 35, Code: "BG", Description: "Bulgaria"},
		{Id: 36, Code: "BF", Description: "Burkina Faso"},
		{Id: 37, Code: "BI", Description: "Burundi"},
		{Id: 38, Code: "KH", Description: "Cambodia"},
		{Id: 39, Code: "CM", Description: "Cameroon"},
		{Id: 40, Code: "CA", Description: "Canada"},
		{Id: 41, Code: "CV", Description: "Cape Verde"},
		{Id: 42, Code: "KY", Description: "Cayman Islands"},
		{Id: 43, Code: "CF", Description: "Central African Republic"},
		{Id: 44, Code: "TD", Description: "Chad"},
		{Id: 45, Code: "CL", Description: "Chile"},
		{Id: 46, Code: "CN", Description: "China"},
		{Id: 47, Code: "CX", Description: "Christmas Island"},
		{Id: 48, Code: "CC", Description: "Cocos (Keeling) Islands"},
		{Id: 49, Code: "CO", Description: "Colombia"},
		{Id: 50, Code: "KM", Description: "Comoros"},
		{Id: 51, Code: "CG", Description: "Congo"},
		{Id: 52, Code: "CD", Description: "Congo, The Democratic Republic Of The"},
		{Id: 53, Code: "CK", Description: "Cook Islands"},
		{Id: 54, Code: "CR", Description: "Costa Rica"},
		{Id: 55, Code: "CI", Description: "Cote D'Ivoire"},
		{Id: 56, Code: "HR", Description: "Croatia"},
		{Id: 57, Code: "CU", Description: "Cuba"},
		{Id: 58, Code: "CW", Description: "Curacao"},
		{Id: 59, Code: "CY", Description: "Cyprus"},
		{Id: 60, Code: "CZ", Description: "Czech Republic"},
		{Id: 61, Code: "DK", Description: "Denmark"},
		{Id: 62, Code: "DJ", Description: "Djibouti"},
		{Id: 63, Code: "DM", Description: "Dominica"},
		{Id: 64, Code: "DO", Description: "Dominican Republic"},
		{Id: 65, Code: "EC", Description: "Ecuador"},
		{Id: 66, Code: "EG", Description: "Egypt"},
		{Id: 67, Code: "SV", Description: "El Salvador"},
		{Id: 68, Code: "GQ", Description: "Equatorial Guinea"},
		{Id: 69, Code: "ER", Description: "Eritrea"},
		{Id: 70, Code: "EE", Description: "Estonia"},
		{Id: 71, Code: "ET", Description: "Ethiopia"},
		{Id: 72, Code: "FK", Description: "Falkland Islands (Malvinas)"},
		{Id: 73, Code: "FO", Description: "Faroe Islands"},
		{Id: 74, Code: "FJ", Description: "Fiji"},
		{Id: 75, Code: "FI", Description: "Finland"},
		{Id: 76, Code: "FR", Description: "France"},
		{Id: 77, Code: "GF", Description: "French Guiana"},
		{Id: 78, Code: "PF", Description: "French Polynesia"},
		{Id: 79, Code: "TF", Description: "French Southern Territories"},
		{Id: 80, Code: "GA", Description: "Gabon"},
		{Id: 81, Code: "GM", Description: "Gambia"},
		{Id: 82, Code: "GE", Description: "Georgia"},
		{Id: 83, Code: "DE", Description: "Germany"},
		{Id: 84, Code: "GH", Description: "Ghana"},
		{Id: 85, Code: "GI", Description: "Gibraltar"},
		{Id: 86, Code: "GR", Description: "Greece"},
		{Id: 87, Code: "GL", Description: "Greenland"},
		{Id: 88, Code: "GD", Description: "Grenada"},
		{Id: 89, Code: "GP", Description: "Guadeloupe"},
		{Id: 90, Code: "GU", Description: "Guam"},
		{Id: 91, Code: "GT", Description: "Guatemala"},
		{Id: 92, Code: "GG", Description: "Guernsey"},
		{Id: 93, Code: "GN", Description: "Guinea"},
		{Id: 94, Code: "GW", Description: "Guinea-Bissau"},
		{Id: 95, Code: "GY", Description: "Guyana"},
		{Id: 96, Code: "HT", Description: "Haiti"},
		{Id: 97, Code: "HM", Description: "Heard Island And Mcdonald Islands"},
		{Id: 98, Code: "HN", Description: "Honduras"},
		{Id: 99, Code: "HK", Description: "Hong Kong"},
		{Id: 100, Code: "HU", Description: "Hungary"},
		{Id: 101, Code: "IS", Description: "Iceland"},
		{Id: 102, Code: "IN", Description: "India"},
		{Id: 103, Code: "ID", Description: "Indonesia"},
		{Id: 104, Code: "IR", Description: "Iran, Islamic Republic Of"},
		{Id: 105, Code: "IQ", Description: "Iraq"},
		{Id: 106, Code: "IE", Description: "Ireland"},
		{Id: 107, Code: "IM", Description: "Isle Of Man"},
		{Id: 108, Code: "IL", Description: "Israel"},
		{Id: 109, Code: "IT", Description: "Italy"},
		{Id: 110, Code: "JM", Description: "Jamaica"},
		{Id: 111, Code: "JP", Description: "Japan"},
		{Id: 112, Code: "JE", Description: "Jersey"},
		{Id: 113, Code: "JO", Description: "Jordan"},
		{Id: 114, Code: "KZ", Description: "Kazakhstan"},
		{Id: 115, Code: "KE", Description: "Kenya"},
		{Id: 116, Code: "KI", Description: "Kiribati"},
		{Id: 117, Code: "KP", Description: "Korea, Democratic People's Republic Of"},
		{Id: 118, Code: "KR", Description: "Korea, Republic Of"},
		{Id: 119, Code: "KW", Description: "Kuwait"},
		{Id: 120, Code: "KG", Description: "Kyrgyzstan"},
		{Id: 121, Code: "LA", Description: "Lao People's Democratic Republic"},
		{Id: 122, Code: "LV", Description: "Latvia"},
		{Id: 123, Code: "LB", Description: "Lebanon"},
		{Id: 124, Code: "LS", Description: "Lesotho"},
		{Id: 125, Code: "LR", Description: "Liberia"},
		{Id: 126, Code: "LY", Description: "Libyan Arab Jamahiriya"},
		{Id: 127, Code: "LI", Description: "Liechtenstein"},
		{Id: 128, Code: "LT", Description: "Lithuania"},
		{Id: 129, Code: "LU", Description: "Luxembourg"},
		{Id: 130, Code: "MO", Description: "Macao"},
		{Id: 131, Code: "MK", Description: "Macedonia, The Former Yugoslav Republic Of"},
		{Id: 132, Code: "MG", Description: "Madagascar"},
		{Id: 133, Code: "MW", Description: "Malawi"},
		{Id: 134, Code: "MY", Description: "Malaysia"},
		{Id: 135, Code: "MV", Description: "Maldives"},
		{Id: 136, Code: "ML", Description: "Mali"},
		{Id: 137, Code: "MT", Description: "Malta"},
		{Id: 138, Code: "MH", Description: "Marshall Islands"},
		{Id: 139, Code: "MQ", Description: "Martinique"},
		{Id: 140, Code: "MR", Description: "Mauritania"},
		{Id: 141, Code: "MU", Description: "Mauritius"},
		{Id: 142, Code: "YT", Description: "Mayotte"},
		{Id: 143, Code: "MX", Description: "Mexico"},
		{Id: 144, Code: "FM", Description: "Micronesia, Federated States Of"},
		{Id: 145, Code: "MD", Description: "Moldova, Republic Of"},
		{Id: 146, Code: "MC", Description: "Monaco"},
		{Id: 147, Code: "MN", Description: "Mongolia"},
		{Id: 148, Code: "ME", Description: "Montenegro"},
		{Id: 149, Code: "MS", Description: "Montserrat"},
		{Id: 150, Code: "MA", Description: "Morocco"},
		{Id: 151, Code: "MZ", Description: "Mozambique"},
		{Id: 152, Code: "MM", Description: "Myanmar"},
		{Id: 153, Code: "nan", Description: "Namibia"},
		{Id: 154, Code: "NR", Description: "Nauru"},
		{Id: 155, Code: "NP", Description: "Nepal"},
		{Id: 156, Code: "NL", Description: "Netherlands"},
		{Id: 157, Code: "AN", Description: "Netherlands Antilles"},
		{Id: 158, Code: "NC", Description: "New Caledonia"},
		{Id: 159, Code: "NZ", Description: "New Zealand"},
		{Id: 160, Code: "NI", Description: "Nicaragua"},
		{Id: 161, Code: "NE", Description: "Niger"},
		{Id: 162, Code: "NG", Description: "Nigeria"},
		{Id: 163, Code: "NU", Description: "Niue"},
		{Id: 164, Code: "NF", Description: "Norfolk Island"},
		{Id: 165, Code: "MP", Description: "Northern Mariana Islands"},
		{Id: 166, Code: "NO", Description: "Norway"},
		{Id: 167, Code: "XX", Description: "Not categorised"},
		{Id: 168, Code: "OM", Description: "Oman"},
		{Id: 169, Code: "ZZ", Description: "Others"},
		{Id: 170, Code: "PK", Description: "Pakistan"},
		{Id: 171, Code: "PW", Description: "Palau"},
		{Id: 172, Code: "PS", Description: "Palestinian Territory, Occupied"},
		{Id: 173, Code: "PA", Description: "Panama"},
		{Id: 174, Code: "PG", Description: "Papua New Guinea"},
		{Id: 175, Code: "PY", Description: "Paraguay"},
		{Id: 176, Code: "PE", Description: "Peru"},
		{Id: 177, Code: "PH", Description: "Philippines"},
		{Id: 178, Code: "PN", Description: "Pitcairn"},
		{Id: 179, Code: "PL", Description: "Poland"},
		{Id: 180, Code: "PT", Description: "Portugal"},
		{Id: 181, Code: "PR", Description: "Puerto Rico"},
		{Id: 182, Code: "QA", Description: "Qatar"},
		{Id: 183, Code: "RE", Description: "Reunion Island"},
		{Id: 184, Code: "RO", Description: "Romania"},
		{Id: 185, Code: "RU", Description: "Russian Federation"},
		{Id: 186, Code: "RW", Description: "Rwanda"},
		{Id: 187, Code: "BL", Description: "Saint Barthelemy"},
		{Id: 188, Code: "SH", Description: "Saint Helena, Ascension And Tristan da Cunha"},
		{Id: 189, Code: "KN", Description: "Saint Kitts And Nevis"},
		{Id: 190, Code: "LC", Description: "Saint Lucia"},
		{Id: 191, Code: "MF", Description: "Saint Martin"},
		{Id: 192, Code: "PM", Description: "Saint Pierre And Miquelon"},
		{Id: 193, Code: "VC", Description: "Saint Vincent And The Grenadines"},
		{Id: 194, Code: "WS", Description: "Samoa"},
		{Id: 195, Code: "SM", Description: "San Marino"},
		{Id: 196, Code: "ST", Description: "Sao Tome And Principe"},
		{Id: 197, Code: "SA", Description: "Saudi Arabia"},
		{Id: 198, Code: "SN", Description: "Senegal"},
		{Id: 199, Code: "RS", Description: "Serbia"},
		{Id: 200, Code: "SC", Description: "Seychelles"},
		{Id: 201, Code: "SL", Description: "Sierra Leone"},
		{Id: 202, Code: "SG", Description: "Singapore"},
		{Id: 203, Code: "SX", Description: "Sint Maarten (Dutch Part)"},
		{Id: 204, Code: "SK", Description: "Slovakia"},
		{Id: 205, Code: "SI", Description: "Slovenia"},
		{Id: 206, Code: "SB", Description: "Solomon Islands"},
		{Id: 207, Code: "SO", Description: "Somalia"},
		{Id: 208, Code: "ZA", Description: "South Africa"},
		{Id: 209, Code: "GS", Description: "South Georgia And The South Sandwich Islands"},
		{Id: 210, Code: "SS", Description: "South Sudan"},
		{Id: 211, Code: "ES", Description: "Spain"},
		{Id: 212, Code: "LK", Description: "Sri Lanka"},
		{Id: 213, Code: "SD", Description: "Sudan"},
		{Id: 214, Code: "SR", Description: "Suriname"},
		{Id: 215, Code: "SJ", Description: "Svalbard And Jan Mayen Islands"},
		{Id: 216, Code: "SZ", Description: "Swaziland"},
		{Id: 217, Code: "SE", Description: "Sweden"},
		{Id: 218, Code: "CH", Description: "Switzerland"},
		{Id: 219, Code: "SY", Description: "Syrian Arab Republic"},
		{Id: 220, Code: "TW", Description: "Taiwan, Province Of China"},
		{Id: 221, Code: "TJ", Description: "Tajikistan"},
		{Id: 222, Code: "TZ", Description: "Tanzania, United Republic Of"},
		{Id: 223, Code: "TH", Description: "Thailand"},
		{Id: 224, Code: "TL", Description: "Timor-Leste"},
		{Id: 225, Code: "TG", Description: "Togo"},
		{Id: 226, Code: "TK", Description: "Tokelau"},
		{Id: 227, Code: "TO", Description: "Tonga"},
		{Id: 228, Code: "TT", Description: "Trinidad And Tobago"},
		{Id: 229, Code: "TN", Description: "Tunisia"},
		{Id: 230, Code: "TR", Description: "Turkey"},
		{Id: 231, Code: "TM", Description: "Turkmenistan"},
		{Id: 232, Code: "TC", Description: "Turks And Caicos Islands"},
		{Id: 233, Code: "TV", Description: "Tuvalu"},
		{Id: 234, Code: "UG", Description: "Uganda"},
		{Id: 235, Code: "UA", Description: "Ukraine"},
		{Id: 236, Code: "AE", Description: "United Arab Emirates"},
		{Id: 237, Code: "GB", Description: "United Kingdom"},
		{Id: 238, Code: "US", Description: "United States"},
		{Id: 239, Code: "UM", Description: "United States Minor Outlying Islands"},
		{Id: 240, Code: "UY", Description: "Uruguay"},
		{Id: 241, Code: "UZ", Description: "Uzbekistan"},
		{Id: 242, Code: "VU", Description: "Vanuatu"},
		{Id: 243, Code: "VA", Description: "Vatican City State"},
		{Id: 244, Code: "VE", Description: "Venezuela, Bolivarian Republic Of"},
		{Id: 245, Code: "VN", Description: "Viet Nam"},
		{Id: 246, Code: "VG", Description: "Virgin Islands, British"},
		{Id: 247, Code: "VI", Description: "Virgin Islands, U.S."},
		{Id: 248, Code: "WF", Description: "Wallis And Futuna"},
		{Id: 249, Code: "EH", Description: "Western Sahara"},
		{Id: 250, Code: "YE", Description: "Yemen"},
		{Id: 251, Code: "ZM", Description: "Zambia"},
		{Id: 252, Code: "ZW", Description: "Zimbabwe"},
	}

	for _, lis := range l {
		resp := s.db.Store.FirstOrCreate(&lis)

		if resp.Error != nil {
			utils.Log.Error(resp.Error)
		}
	}
	return nil
}
